AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Storage Security

Parameters:
  SNSTopic:
    Type: String
    Description: The SNS Topic to connect Trend Micro Storage Security with Lambda, Specify an existing SNS Topic
    

Resources:
  filterBucketObjactsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: filter_bucket_objacts_lambda
      CodeUri: s3://aws-serverless-storage-security-filter-bucket-objects/filter_bucket_objects_1.0.0.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 3008
      Timeout: 120
      Tracing: Active
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "${fsspromote}"
        - S3CrudPolicy:
            BucketName: !Sub "${fssquarantine}"
      Environment:
        Variables:
          PROMOTEBUCKET: !Ref fsspromote
          QUARANTINEBUCKET: !Ref fssquarantine
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic

  fsspromote:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: fbopromote

  fssquarantine:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: fboquarantine





